export const allProducts = [
  {
    id: 1,
    name: "Cheese Burger Cheese",
    imageUrl: "src/assets/images/Cheese Burger.png",
    description: "Our #1 bestseller of all time, juicy beef patty with melted cheddar.",
    price: 8.99,
    orders: 1200,
    rank: 1,
    bgColor: "white",
  },
  {
    id: 2,
    name: "Crispyest Fries",
    imageUrl: "src/assets/images/French Fries.png",
    description: "Golden, crispy perfection, epicly seasoned.",
    price: 3.99,
    orders: 980,
    rank: 2,
    bgColor: "white",
  },
  {
    id: 3,
    name: "Chicken Nuggets Extra",
    imageUrl: "src/assets/images/Chicken Nuggets.png",
    description: "Extra crispy on the outside, tender on the inside.",
    price: 6.99,
    orders: 875,
    rank: 3,
    bgColor: "white",
  },
  {
    id: 4,
    name: "Turbo Fries",
    imageUrl: "src/assets/images/French Fries.png",
    description: "Turbo good.",
    price: 6.66,
    orders: 980,
    rank: 4,
    bgColor: "white",
  },
];
