export const mostBuyedProducts = [
  {
    id: 1,
    name: "Cheese Burger",
    imageUrl: "src/assets/images/Cheese Burger.png",
    description: "Our #1 bestseller, juicy beef patty with melted cheddar.",
    price: 8.99,
    orders: 1200,
    rank: 1,
    bgColor: "white",
  },
  {
    id: 2,
    name: "Crispy Fries",
    imageUrl: "src/assets/images/French Fries.png",
    description: "Golden, crispy perfection, perfectly seasoned.",
    price: 3.99,
    orders: 980,
    rank: 2,
    bgColor: "white",
  },
  {
    id: 3,
    name: "Chicken Nuggets",
    imageUrl: "src/assets/images/Chicken Nuggets.png",
    description: "Crispy on the outside, tender on the inside.",
    price: 6.99,
    orders: 875,
    rank: 3,
    bgColor: "white",
  },
];
